name=NV3047
version=1.0.0
author=AirysDark
maintainer=AirysDark
sentence=High-performance low-level HAL display driver engine for CrowPanel 4.3.
paragraph=Features dynamic 32-bit hardware canvas clearing optimizations, safe edge-boundary clipping blitters, precise microsecond cadence-locked page flipping, and calibrated multi-sample touch tracking remapping matrices for the ESP32-S3.
category=Display
url=https://github.com/AirysDark/NV3047_drivers
architectures=esp32s3
includes=NV3047_Driver.h
