#pragma once

#define LV_COLOR_DEPTH 16

#define LV_COLOR_16_SWAP 0

#define LV_MEM_CUSTOM 0

#define LV_MEM_SIZE (64U * 1024U)

#define LV_USE_LOG 0

#define LV_USE_ASSERT_NULL 1
#define LV_USE_ASSERT_MALLOC 1
#define LV_USE_ASSERT_STYLE 0

#define LV_USE_PERF_MONITOR 1

#define LV_TICK_CUSTOM 0

#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_18 1
#define LV_FONT_MONTSERRAT_22 1
#define LV_FONT_MONTSERRAT_28 1

#define LV_USE_LABEL 1
#define LV_USE_BTN 1
#define LV_USE_ARC 1
#define LV_USE_BAR 1
#define LV_USE_SLIDER 1

#define LV_USE_DEMO_WIDGETS 1